<a href="https://colab.research.google.com/github/varalakshmimuppirisetty-beep/hospital-performance-analysis/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

step 1 : loading required libraries

In [18]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

step 2: uploading dataset

In [19]:
df = pd.read_csv('FY_2026_Hospital_Readmissions_Reduction_Program_Hospital.csv')
df.head()

,Facility Name,Facility ID,State,Measure Name,Number of Discharges,Footnote,Excess Readmission Ratio,Predicted Readmission Rate,Expected Readmission Rate,Number of Readmissions,Start Date,End Date
0,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,READM-30-HIP-KNEE-HRRP,NaN,NaN,0.9875,4.5734,4.6311,Too Few to Report,07/01/2021,06/30/2024
1,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,READM-30-CABG-HRRP,137.0,NaN,0.9531,10.3960,10.9078,13,07/01/2021,06/30/2024
2,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,READM-30-AMI-HRRP,273.0,NaN,0.9370,13.2998,14.1948,33,07/01/2021,06/30/2024
3,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,READM-30-COPD-HRRP,122.0,NaN,0.9823,16.6384,16.9389,19,07/01/2021,06/30/2024
4,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,READM-30-PN-HRRP,507.0,NaN,0.9871,15.7529,15.9591,79,07/01/2021,06/30/2024

Step 3: Understanding the Dataset

In [20]:
df.shape

(18330, 12)

In [21]:
df.columns

Index(['Facility Name', 'Facility ID', 'State', 'Measure Name',
       'Number of Discharges', 'Footnote', 'Excess Readmission Ratio',
       'Predicted Readmission Rate', 'Expected Readmission Rate',
       'Number of Readmissions', 'Start Date', 'End Date'],
      dtype='object')

In [22]:
df.dtypes

Facility Name                  object
Facility ID                     int64
State                          object
Measure Name                   object
Number of Discharges          float64
Footnote                      float64
Excess Readmission Ratio      float64
Predicted Readmission Rate    float64
Expected Readmission Rate     float64
Number of Readmissions         object
Start Date                     object
End Date                       object
dtype: object

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18330 entries, 0 to 18329
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Facility Name               18330 non-null  object
 1   Facility ID                 18330 non-null  int64
 2   State                       18330 non-null  object
 3   Measure Name                18330 non-null  object
 4   Number of Discharges        8242 non-null   float64
 5   Footnote                    6987 non-null   float64
 6   Excess Readmission Ratio    11720 non-null  float64
 7   Predicted Readmission Rate  11720 non-null  float64
 8   Expected Readmission Rate   11720 non-null  float64
 9   Number of Readmissions      11720 non-null  object
 10  Start Date                  18330 non-null  object
 11  End Date                    18330 non-null  object
dtypes: float64(5), int64(1), object(6)
memory usage: 1.7+ MB

In [24]:
df.describe()

,Facility ID,Number of Discharges,Footnote,Excess Readmission Ratio,Predicted Readmission Rate,Expected Readmission Rate
count,18330.000000,8242.000000,6987.000000,11720.000000,11720.000000,11720.000000
mean,262031.979378,283.416282,4.550308,1.001777,14.981461,14.947978
std,164868.122655,270.929023,6.181702,0.082050,4.763655,4.620865
min,10001.000000,0.000000,1.000000,0.469800,1.908000,3.087600
25%,110069.000000,117.000000,1.000000,0.958200,12.529550,12.623750
50%,250048.000000,198.000000,5.000000,0.997300,15.860150,15.856550
75%,390138.000000,358.000000,5.000000,1.042300,18.418500,18.500925
max,670342.000000,3672.000000,29.000000,1.629700,28.164300,26.865400

In [25]:
df.isnull().sum()

Facility Name                     0
Facility ID                       0
State                             0
Measure Name                      0
Number of Discharges          10088
Footnote                      11343
Excess Readmission Ratio       6610
Predicted Readmission Rate     6610
Expected Readmission Rate      6610
Number of Readmissions         6610
Start Date                        0
End Date                          0
dtype: int64

Step 4: Data Cleaning

In [27]:
df = df.drop(columns=['Footnote'])
df.shape

(18330, 11)

In [28]:
df = df.dropna(subset=['Excess Readmission Ratio'])
df.shape

(11720, 11)

Convert Number of Readmissions to Numeric

In [29]:
df['Number of Readmissions'] = pd.to_numeric(df['Number of Readmissions'], errors='coerce')
df['Number of Readmissions'].dtype

dtype('float64')

Convert Dates to Proper Format

In [30]:
df['Start Date'] = pd.to_datetime(df['Start Date'])
df['End Date'] = pd.to_datetime(df['End Date'])
df[['Start Date', 'End Date']].dtypes

Start Date    datetime64[ns]
End Date      datetime64[ns]
dtype: object

Fill Missing Number of Discharges

In [31]:
median_discharges = df['Number of Discharges'].median()
print('Median discharges:', median_discharges)

df['Number of Discharges'] = df['Number of Discharges'].fillna(median_discharges)

Median discharges: 203.0

Confirm Everything is Clean

In [32]:
df.isnull().sum()

Facility Name                    0
Facility ID                      0
State                            0
Measure Name                     0
Number of Discharges             0
Excess Readmission Ratio         0
Predicted Readmission Rate       0
Expected Readmission Rate        0
Number of Readmissions        3683
Start Date                       0
End Date                         0
dtype: int64

In [33]:
print('Shape:', df.shape)
print('\nMissing values:')
print(df.isnull().sum())

Shape: (11720, 11)

Missing values:
Facility Name                    0
Facility ID                      0
State                            0
Measure Name                     0
Number of Discharges             0
Excess Readmission Ratio         0
Predicted Readmission Rate       0
Expected Readmission Rate        0
Number of Readmissions        3683
Start Date                       0
End Date                         0
dtype: int64